-- Nebula OS: базовий конфіг Hyprland (монітори, інпут, лейаут, автозапуск, хоткеї).
-- Живий файл (crew/hyprland/default.nix підключає його через mkOutOfStoreSymlink) —
-- редагується напряму, Hyprland підхоплює зміни на льоту, без `nh os switch`.
--
-- Візуальний tweaking (blur/анімації/border/rounding) — окремо, у tweaks.lua,
-- підключений нижче через require.

hl.config({ autogenerated = false })

-- RetroArch (core/packages.nix) без цього тягне XWayland через SDL2 -- тут,
-- а не в home.sessionVariables (crew/theming.nix), навмисно: глобально
-- SDL_VIDEODRIVER=wayland зламав би той самий RetroArch під bspwm (X11-сесія,
-- Wayland-дисплея просто нема, SDL без фолбеку впаде на старті).
hl.env("SDL_VIDEODRIVER", "wayland")

-- Нового заліза (Arc A770) ще нема — поки що "preferred", auto-позиція.
-- Повернутись і прописати точний режим/позицію, коли прийде новий білд.
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })

hl.config({
  input = {
    -- Та сама розкладка, що й у core/system.nix (services.xserver.xkb) —
    -- тримати обидві копії в синхроні при зміні розкладки.
    kb_layout = "us,ua,de",
    kb_options = "grp:alt_shift_toggle",
    -- follow_mouse=0 -- перевірено вдруге, з живим EE2, PoE все одно
    -- перехоплював контроль. Не той фікс, прибрано остаточно. Реальна
    -- причина зникання попапу при наведенні -- власна uiohook-логіка
    -- застосунку (AreaTracker: рух миші без утримання Ctrl понад
    -- closeThreshold = сигнал "сховати", ніяк не пов'язано з Hyprland-
    -- фокусом), а "PoE перехоплює контроль на інших workspace" -- та сама
    -- причина, що й із poe-price-check: `pin = true` (див. нижче).
  },
})

-- hyprland-scroll-overview МУСИТЬ завантажитись ДО require("tweaks") нижче --
-- живо впіймана помилка: tweaks.lua виставляє plugin.scrolloverview.* через
-- hl.config, а Hyprland парсить конфіг (і виконує і require, і hl.on-колбеки)
-- ПОСЛІДОВНО зверху вниз на старті сесії. Коли завантаження плагіна стояло
-- всередині hl.on("hyprland.start", ...) НИЖЧЕ require("tweaks"), на
-- холодному старті Hyprland доходив до tweaks.lua раніше, ніж плагін встигав
-- зареєструвати свої конфіг-ключі -- "unknown config key 'plugin.scrolloverview.*'".
-- На живому hyprctl reload (без повного рестарту сесії) це не ловилось,
-- бо плагін там уже залишався завантаженим з попереднього старту.
-- hyprspace раніше був у hl.on("hyprland.start") саме тому, що сам нічого не
-- конфігурував через hl.config -- порядок йому був байдужий.
hl.plugin.load("/etc/profiles/per-user/ryudzyn/lib/libscrolloverview.so")

require("tweaks")

local terminal = "wezterm"

hl.on("hyprland.start", function()
    -- graphical-session.target (те, до чого прив'язаний home-manager-івський
    -- noctalia.service через WantedBy) ніколи сам не активується для
    -- Hyprland на NixOS, а `systemctl --user start graphical-session.target`
    -- напряму падає з "RefuseManualStart" -- це системний static-таргет,
    -- його не можна стартувати вручну. Живо перевірено: єдиний робочий шлях
    -- -- стартувати сам noctalia.service напряму, в обхід таргету.
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user start noctalia.service")
    -- xdg-desktop-portal.service -- та сама історія з "мертвим"
    -- graphical-session.target, тільки гірша: юніт має Requisite=
    -- (не PartOf=/After=, як noctalia.service), тому звичайний
    -- `systemctl --user start` миттєво провалюється з "Dependency failed"
    -- щоразу, коли БУДЬ-ЯКИЙ застосунок пробує достукатись до
    -- org.freedesktop.portal.Desktop через D-Bus-активацію (Discord
    -- screen-share мовчки "не реагував" саме через це -- сам D-Bus-виклик
    -- ніколи не доходив до живого сервісу; live виявлено 2026-09-29).
    -- --job-mode=ignore-dependencies обходить саме Requisite-перевірку.
    hl.exec_cmd("systemctl --user start --job-mode=ignore-dependencies xdg-desktop-portal.service")
    hl.exec_cmd(terminal)
    -- Фіксована тепла температура замість розкладу день/ніч -- hyprsunset
    -- сам по собі без конфіг-файлу не знає, коли вмикати/вимикати профіль;
    -- розклад можна додати пізніше через ~/.config/hypr/hyprsunset.conf,
    -- якщо цього виявиться мало.
    hl.exec_cmd("hyprsunset -t 4500")
    -- Агент автентифікації polkit -- без нього немає GUI-діалогу пароля для
    -- pkexec/"Format" у GNOME Disks тощо (живо виявлено 2026-09-29, деталі в
    -- default.nix біля pkgs.hyprpolkitagent). Через systemd user-юніт пакета
    -- (systemd.user.packages у default.nix), не напряму по шляху бінарника
    -- -- перша спроба (жорсткий шлях на libexec/) провалилась, бо цей
    -- каталог не потрапляє в per-user профіль (на відміну від lib/, як у
    -- hyprspace). WantedBy=graphical-session.target у самому юніті не
    -- спрацьовує тут (та сама причина, що й для noctalia.service вище),
    -- тому старт явний.
    hl.exec_cmd("systemctl --user start hyprpolkitagent.service")
end)

-- Awakened PoE Trade -- встановлений, оверлей/тултіп працює (no_blur,
-- клікабельні кнопки гри через --ozone-platform=x11, дивись
-- crew/hyprland/default.nix). Раніше тут стояв no_focus, і з ним Ctrl+D не
-- працював -- висновок був "Hyprland 0.55.4 не виставляє _NET_ACTIVE_WINDOW
-- для XWayland, не лагодиться". 2026-09-27: Exiled Exchange 2 (той самий
-- electron-overlay-window/uiohook-napi код, PoE2-форк Awakened) отримав
-- ІДЕНТИЧНЕ правило БЕЗ no_focus -- і Ctrl+D в ньому працює одразу, живо
-- підтверджено. Тобто справжня причина провалу в Awakened, схоже, був саме
-- no_focus (заважав XWM-у Hyprland коректно віддавати фокус назад грі), а
-- не непоборний ліміт компоситора -- прибрано, ПОТРІБЕН повторний живий
-- тест Ctrl+D в PoE1.
-- pin теж прибрано (та сама причина, що й у poe-price-check нижче: pinned
-- вікно "тікає" на всі workspace одночасно, і клік на ІНШОМУ workspace
-- плутано роутиться на гру -- живо підтверджено з EE2 2026-09-27).
hl.window_rule({
    name  = "awakened-poe-trade-overlay",
    match = { class = "^awakened-poe-trade$" },

    float = true,
    no_blur = true,
    no_shadow = true,
    border_size = 0,
})

-- Exiled Exchange 2 (PoE2) -- той самий рецепт, АЛЕ без no_focus (див.
-- коментар вище над awakened-poe-trade-overlay) -- живо підтверджено:
-- Ctrl+D працює. class з .desktop (StartupWMClass=Exiled Exchange 2) міг
-- відрізнятись від реального runtime app-id (як і в Awakened, де
-- StartupWMClass не збігався з "awakened-poe-trade") -- обидва варіанти
-- про всяк випадок.
hl.window_rule({
    name  = "exiled-exchange-2-overlay",
    match = { class = "^Exiled Exchange 2$" },

    float = true,
    no_blur = true,
    no_shadow = true,
    border_size = 0,
})
hl.window_rule({
    name  = "exiled-exchange-2-overlay-lc",
    match = { class = "^exiled-exchange-2$" },

    float = true,
    no_blur = true,
    no_shadow = true,
    border_size = 0,
})

-- Рулетка (surf) -- floating, розмір під контент (колесо 360px + кнопки/
-- редактор списку), по центру екрана, а не на весь tiled-простір.
hl.window_rule({
    name  = "roulette-surf",
    match = { class = "^Surf$" },

    float = true,
    size  = "460 700",
    center = true,
})

-- Калькулятор (Qalculate) -- floating, компактний розмір замість
-- дефолтного 1261x1382 (tiled на весь простір).
hl.window_rule({
    name  = "qalculate-gtk",
    match = { class = "^qalculate-gtk$" },

    float = true,
    size  = "460 620",
    center = true,
})

-- Discord video-call popout -- завжди float+pin (PiP-стиль, поверх усього).
-- Match за initial_title, НЕ за title: title міняється на назву каналу
-- одразу після відкриття, а Hyprland-івський windowrule перевіряє
-- клас/тайтл лише в момент СТВОРЕННЯ вікна (задокументований лімітейшн,
-- нема динамічного re-match на зміну title) -- initial_title фіксує
-- "Discord Popout" назавжди, ще до цієї зміни. class лишається "discord",
-- як і в головного вікна, тож саме тільки за title/class не розрізнити.
hl.window_rule({
    name  = "discord-popout",
    match = { initial_title = "^Discord Popout$" },

    float = true,
    pin = true,
})

-- zen-browser Picture-in-Picture -- та сама історія: class лишається "zen"
-- (як і головне вікно браузера), тож розрізняє тільки initial_title.
-- Живо підтверджено (2026-09-27): нативний Wayland (xwayland:0), pin не
-- ловить клік на інших workspace -- той самий висновок, що й з Discord
-- popout вище (баг hyprwm/Hyprland#4135 специфічний саме для XWayland).
hl.window_rule({
    name  = "zen-pip",
    match = { initial_title = "^Picture-in-Picture$" },

    float = true,
    pin = true,
})

-- poe-price-check -- tkinter override_redirect вікно. Пробували windowrule
-- (pin, stay_focused, окремо й разом) -- жоден комбо не прибрав ні
-- неклікабельність, ні "втечу" кліків на PoE при перемиканні workspace, поки
-- попап показаний. Висновок: це не лагодиться на рівні windowrule --
-- override_redirect / XWayland-легасі, яке Hyprland просто не розуміє так,
-- як X11 (підтверджено самим мейнтейнером Hyprland, issue #2365). Реальний
-- фікс -- переписати UI на GTK + layer-shell (нативний Wayland), окремий,
-- більший follow-up.

-- Єдиний список біндів: кожен запис одразу несе опис для довідки нижче
-- (nebula-keybind-help-hypr), той самий принцип, що й `keybinds` у
-- crew/bspwm.nix -- опис і реальний бінд генеруються з одного джерела, тож
-- ніколи не розійдуться. Робочі простори 1-9 (цикл нижче) свідомо лишені
-- окремо -- 18 однакових по формі записів тут тільки заважали б читати.
local binds = {
    -- Основні
    { key = "SUPER + Return", desc = "Термінал (wezterm)", action = hl.dsp.exec_cmd(terminal) },
    { key = "SUPER + D", desc = "Запуск застосунків (Noctalia)", action = hl.dsp.exec_cmd("noctalia msg panel-toggle launcher") },
    -- poe-price-check -- основний прайс-чекер на Hyprland (crew/poe-price-check.nix);
    -- нативний Hyprland-бінд, який не залежить від фокус-трекінгу
    -- XWayland/electron-overlay-window взагалі.
    { key = "SUPER + P", desc = "poe-price-check (прайс-чекер PoE)", action = hl.dsp.exec_cmd("poe-price-check") },
    { key = "SUPER + Q", desc = "Закрити вікно", action = hl.dsp.window.close() },
    { key = "SUPER + F", desc = "Fullscreen для вікна", action = hl.dsp.window.fullscreen({}) },
    { key = "SUPER + SHIFT + Space", desc = "Toggle floating для вікна", action = hl.dsp.window.float({}) },
    -- Pin -- закріпити плаваюче вікно поверх усіх воркспейсів (той самий
    -- super+shift+p, що й always-on-top у crew/bspwm.nix). Не floating-вікно
    -- pin просто ігнорує -- спершу SUPER+SHIFT+Space.
    { key = "SUPER + SHIFT + P", desc = "Pin — закріпити плаваюче вікно поверх усіх воркспейсів", action = hl.dsp.window.pin() },

    -- Режими (crew/modes.nix) -- розкладають набір застосунків по workspace.
    { key = "SUPER + F1", desc = "Режим «робота» — codium/kitty/zen, сповіщення на паузі", action = hl.dsp.exec_cmd("mode-work") },
    { key = "SUPER + F2", desc = "Режим «навчання» — anki/goldendict/zen, сповіщення на паузі", action = hl.dsp.exec_cmd("mode-study") },
    { key = "SUPER + F3", desc = "Режим «гра» — steam/discord, сповіщення увімкнено", action = hl.dsp.exec_cmd("mode-play") },

    -- Скріншоти. 2026-09-29: Print віддано під анотований скріншот (satty) --
    -- той, яким реально користуються найчастіше -- а звичайний повноекранний
    -- через Noctalia переїхав на super+Print, щоб не губився. super+shift+g
    -- звільнено під землю (nebula-earth-toggle-wl) нижче.
    { key = "Print", desc = "Анотований скріншот ділянки (satty)", action = hl.dsp.exec_cmd("nebula-screenshot-satty") },
    { key = "SUPER + Print", desc = "Скріншот всього екрана (Noctalia)", action = hl.dsp.exec_cmd("noctalia msg screenshot-fullscreen") },
    { key = "SUPER + SHIFT + S", desc = "Скріншот ділянки → буфер (Noctalia)", action = hl.dsp.exec_cmd("noctalia msg screenshot-region") },
    -- Запис екрана (wf-recorder) -- той самий бінд стартує й зупиняє.
    { key = "SUPER + CTRL + R", desc = "Запис екрана (toggle, wf-recorder)", action = hl.dsp.exec_cmd("nebula-record-toggle") },

    -- Special workspace ("scratchpad") -- прихована робоча область, куди можна
    -- закинути будь-яке вікно і потім показати/сховати одним хоткеєм, як
    -- випадаюча панель. super+shift+s вже зайнятий скріншотом (офіційний
    -- дефолтний приклад Hyprland біндить саме на нього move-в-special), тож
    -- переміщення туди -- на super+ctrl+s.
    { key = "SUPER + S", desc = "Показати/сховати special workspace (scratchpad)", action = hl.dsp.workspace.toggle_special("magic") },
    { key = "SUPER + CTRL + S", desc = "Перекинути вікно у special workspace", action = hl.dsp.window.move({ workspace = "special:magic" }) },

    -- Переміщення/зміна розміру вікна мишею: SUPER + ЛКМ тягне, SUPER + ПКМ
    -- ресайзить (mouse:272/273 -- стандартні коди кнопок з офіційного
    -- дефолтного hyprland.lua, mouse=true обов'язковий для mouse-біндів).
    { key = "SUPER + mouse:272", desc = "Тягнути вікно мишею", action = hl.dsp.window.drag(), opts = { mouse = true } },
    { key = "SUPER + mouse:273", desc = "Ресайз вікна мишею", action = hl.dsp.window.resize(), opts = { mouse = true } },

    -- Порт решти кастомних bspwm-біндів (crew/bspwm.nix) під Hyprland. Де
    -- Noctalia сама вміє те саме (noctalia msg) -- береться саме воно, а не
    -- окремий X11-інструмент/скрипт: лок, power-menu, dpms, theme, wallpaper,
    -- caffeine (=nebula-awake), clipboard-історія, window switcher.
    { key = "SUPER + Escape", desc = "Заблокувати екран (Noctalia)", action = hl.dsp.exec_cmd("noctalia msg session lock") },
    { key = "SUPER + SHIFT + E", desc = "Меню живлення (Noctalia)", action = hl.dsp.exec_cmd("noctalia msg panel-toggle session") },
    { key = "SUPER + SHIFT + Escape", desc = "Вимкнути монітор (dpms)", action = hl.dsp.exec_cmd("noctalia msg dpms-off") },
    { key = "SUPER + N", desc = "Перемкнути світлу/темну тему", action = hl.dsp.exec_cmd("noctalia msg theme-mode-toggle") },
    { key = "SUPER + W", desc = "Вибір шпалер (Noctalia)", action = hl.dsp.exec_cmd("noctalia msg panel-toggle wallpaper") },
    { key = "SUPER + SHIFT + A", desc = "Keep-awake — тумблер (caffeine)", action = hl.dsp.exec_cmd("noctalia msg caffeine-toggle") },
    { key = "SUPER + V", desc = "Історія буфера обміну (Noctalia)", action = hl.dsp.exec_cmd("noctalia msg panel-toggle clipboard") },
    { key = "SUPER + Tab", desc = "Список відкритих вікон (Noctalia)", action = hl.dsp.exec_cmd("noctalia msg window-switcher") },
    -- Той самий SUPER+O, що колись був під hyprspace (видалений як
    -- unfixable) -- тепер під hyprland-scroll-overview, niri-стиль огляду
    -- робочих просторів прокруткою. Плагін сам виставляє функцію в Lua
    -- (hl.plugin.scrolloverview.overview), не через hl.dsp -- обгортка
    -- функцією обов'язкова, бо виклик має відбутись по натисканню клавіші,
    -- а не одразу при зчитуванні конфіга.
    { key = "SUPER + O", desc = "Огляд робочих просторів прокруткою (scroll-overview)", action = function() hl.plugin.scrolloverview.overview("toggle all") end },

    -- Немає нативного еквіваленту в Noctalia -- лишаються окремими
    -- інструментами/скриптами (nwg-look конфігурує GTK-тему застосунків
    -- взагалі, не саму Noctalia, тож не замінюється).
    { key = "SUPER + SHIFT + O", desc = "OCR виділеної ділянки екрана → буфер", action = hl.dsp.exec_cmd("nebula-ocr-wl") },
    { key = "SUPER + SHIFT + X", desc = "Піпетка кольору → hex у буфер", action = hl.dsp.exec_cmd("nebula-color-picker-wl") },
    -- Пікер живих космічних шпалер (Земля/чорна діра/вимкнути) -- Wayland-
    -- порт bspwm-івського nebula-earth-toggle (там був простий xplanet-
    -- тогл), деталі в crew/hyprland/default.nix біля скрипта.
    { key = "SUPER + SHIFT + G", desc = "Космічна шпалера: Земля / чорна діра / вимкнути", action = hl.dsp.exec_cmd("nebula-space-wallpaper-wl") },
    -- Наступний ракурс для АКТИВНОЇ шейдер-шпалери (0°/90°/180°/270°, цикл).
    -- glpaper не приймає live-uniform -- перезапуск із новим CAM_OFFSET, тому
    -- коротка пауза/стрибок анімації при кожному натисканні неминучий
    -- (деталі в default.nix біля nebula-space-wallpaper-rotate).
    { key = "SUPER + G", desc = "Космічна шпалера: наступний ракурс камери (тільки для шейдерів)", action = hl.dsp.exec_cmd("nebula-space-wallpaper-rotate") },
    -- Game mode -- Wayland-порт bspwm-івського nebula-gamemode-toggle:
    -- picom вимкнути не можна (Hyprland сам композитор), тож вимикаємо
    -- blur/анімації через hyprctl keyword; сповіщення -- через Noctalia
    -- (dunst під Hyprland не піднятий). Деталі в default.nix.
    { key = "SUPER + SHIFT + F", desc = "Game mode — вимкнути blur/анімації/сповіщення заради FPS (toggle)", action = hl.dsp.exec_cmd("nebula-gamemode-toggle-wl") },
    { key = "SUPER + SHIFT + T", desc = "Налаштування GTK-теми (nwg-look)", action = hl.dsp.exec_cmd("nwg-look") },
    { key = "SUPER + SHIFT + V", desc = "Мікшер гучності (pavucontrol)", action = hl.dsp.exec_cmd("pavucontrol") },
    -- surf замість xdg-open -- окреме вікно без вкладок/адресного рядка
    -- браузера, той самий готовий HTML/CSS/JS без переписування.
    { key = "SUPER + SHIFT + R", desc = "Рулетка (жарт-застосунок)", action = hl.dsp.exec_cmd(
        "surf file://" .. os.getenv("HOME") .. "/nebula-config/assets/cprogram/roulette.html"
    ) },
    { key = "SUPER + SHIFT + M", desc = "Панель керування мишею Swiftpoint X1", action = hl.dsp.exec_cmd(
        "sh -c 'cd ~/Applications/SwiftpointX1 && ./\"Swiftpoint X1 Control Panel\"'"
    ) },
    { key = "SUPER + SHIFT + C", desc = "Запуск Ascension-мода (dev-клієнт)", action = hl.dsp.exec_cmd(
        'wezterm start --always-new-process -- sh -c "cd ~/Projects/ascension-limitless-progression && nix develop --command ./gradlew runClient"'
    ) },
    { key = "SUPER + Equal", desc = "Калькулятор (Qalculate)", action = hl.dsp.exec_cmd("qalculate-gtk") },

    -- Медіа/яскравість -- ті самі команди, що й у crew/bspwm.nix, портативні
    -- (wpctl/brightnessctl не залежать від X11/bspwm).
    { key = "XF86AudioRaiseVolume", desc = "Гучність +5%", action = hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+") },
    { key = "XF86AudioLowerVolume", desc = "Гучність -5%", action = hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-") },
    { key = "XF86AudioMute", desc = "Toggle mute", action = hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle") },
    { key = "XF86MonBrightnessUp", desc = "Яскравість +5%", action = hl.dsp.exec_cmd("brightnessctl set 5%+") },
    { key = "XF86MonBrightnessDown", desc = "Яскравість -5%", action = hl.dsp.exec_cmd("brightnessctl set 5%-") },

    -- Фокус між вікнами -- стрілки й vim-стиль паралельно (bspwm мав і те, й
    -- те; Hyprland до цього мав лише стрілки -- hjkl додано для паритету).
    { key = "SUPER + Left", desc = "Фокус ліворуч", action = hl.dsp.focus({ direction = "l" }) },
    { key = "SUPER + Right", desc = "Фокус праворуч", action = hl.dsp.focus({ direction = "r" }) },
    { key = "SUPER + Up", desc = "Фокус вгору", action = hl.dsp.focus({ direction = "u" }) },
    { key = "SUPER + Down", desc = "Фокус вниз", action = hl.dsp.focus({ direction = "d" }) },
    { key = "SUPER + H", desc = "Фокус ліворуч (vim-стиль)", action = hl.dsp.focus({ direction = "l" }) },
    { key = "SUPER + L", desc = "Фокус праворуч (vim-стиль)", action = hl.dsp.focus({ direction = "r" }) },
    { key = "SUPER + K", desc = "Фокус вгору (vim-стиль)", action = hl.dsp.focus({ direction = "u" }) },
    { key = "SUPER + J", desc = "Фокус вниз (vim-стиль)", action = hl.dsp.focus({ direction = "d" }) },

    -- Поміняти вікна місцями (bspwm: super+shift+hjkl, bspc node -s) --
    -- hl.window.swap({direction=...}), живий C++-бінд Hyprland, не через
    -- hyprctl dispatch.
    { key = "SUPER + SHIFT + H", desc = "Поміняти вікна місцями — ліворуч", action = hl.dsp.window.swap({ direction = "l" }) },
    { key = "SUPER + SHIFT + L", desc = "Поміняти вікна місцями — праворуч", action = hl.dsp.window.swap({ direction = "r" }) },
    { key = "SUPER + SHIFT + K", desc = "Поміняти вікна місцями — вгору", action = hl.dsp.window.swap({ direction = "u" }) },
    { key = "SUPER + SHIFT + J", desc = "Поміняти вікна місцями — вниз", action = hl.dsp.window.swap({ direction = "d" }) },

    -- Змінити розмір вікна з клавіатури (bspwm: super+ctrl+hjkl, bspc node -z
    -- по кутах; тут простіше -- hl.window.resize приймає дельту в пікселях
    -- по x/y, relative=true). Ресайз мишею (SUPER+ПКМ) вище лишається для
    -- точного підбору розміру, це -- для швидких кроків без миші.
    { key = "SUPER + CTRL + H", desc = "Зменшити ширину вікна", action = hl.dsp.window.resize({ x = -20, y = 0, relative = true }) },
    { key = "SUPER + CTRL + L", desc = "Збільшити ширину вікна", action = hl.dsp.window.resize({ x = 20, y = 0, relative = true }) },
    { key = "SUPER + CTRL + K", desc = "Зменшити висоту вікна", action = hl.dsp.window.resize({ x = 0, y = -20, relative = true }) },
    { key = "SUPER + CTRL + J", desc = "Збільшити висоту вікна", action = hl.dsp.window.resize({ x = 0, y = 20, relative = true }) },
}

for _, b in ipairs(binds) do
    hl.bind(b.key, b.action, b.opts)
end

-- Робочі простори 1-9: SUPER — перейти, SUPER+SHIFT — перекинути вікно
for i = 1, 9 do
    hl.bind("SUPER + " .. i, hl.dsp.focus({ workspace = i }))
    hl.bind("SUPER + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end

-- nebula-keybind-help-hypr: показує весь список біндів (той самий binds
-- вище + окремий рядок для циклу робочих просторів) через fuzzel --dmenu
-- (Wayland-нативний, на відміну від rofi в crew/bspwm.nix) -- лише ПОКАЗУЄ
-- текст, нічого не виконує з вибору, той самий принцип, що й
-- nebula-keybind-help у crew/bspwm.nix.
local helpfile = "/tmp/nebula-hypr-keybinds.txt"
local helpf = io.open(helpfile, "w")
if helpf then
    for _, b in ipairs(binds) do
        helpf:write(b.key .. "  →  " .. b.desc .. "\n")
    end
    helpf:write("SUPER + 1-9  →  Перемкнутись на робочий простір 1-9\n")
    helpf:write("SUPER + SHIFT + 1-9  →  Перекинути вікно на робочий простір 1-9\n")
    helpf:write("SUPER + SHIFT + /  →  Цей список комбінацій\n")
    helpf:close()
end
hl.bind("SUPER + SHIFT + slash", hl.dsp.exec_cmd(
    "sh -c 'cat " .. helpfile .. " | fuzzel --dmenu -p Keybinds: > /dev/null 2>&1'"
))

-- ALT+Tab -- візуальний перемикач вікон через scroll-overview, окремий модуль
-- (crew/hyprland/alttab.lua, той самий require-шлях, що й tweaks вище).
-- submap_universal/release/transparent -- точні прапорці з офіційної вікі
-- плагіна (ALT-Tab-overview), не здогад: submap_universal тримає бінд живим,
-- поки активний submap "scrolloverview" (інакше звичайні біндинги Hyprland
-- глушаться, доки overview відкритий); release+transparent на Alt_L/Alt_R --
-- спрацьовує саме на ВІДПУСКАННЯ клавіші Alt (а не Tab), і не "з'їдає" подію
-- для інших застосунків.
local altTab = require("scripts.alttab")
hl.bind("ALT + Tab", altTab.next, { submap_universal = true })
hl.bind("ALT + Alt_L", altTab.close, { release = true, transparent = true })
hl.bind("ALT + Alt_R", altTab.close, { release = true, transparent = true })

-- scroll-overview: власний submap + динамічні робочі простори
-- (niri-подібне "нескінченне" гортання). Хелпери мусять бути оголошені ДО
-- hl.define_submap нижче -- Lua-замикання захоплює локальні змінні лексично
-- в момент компіляції функції, тож forward-reference на ще не оголошений
-- local не спрацює (був живо впійманий порядок навпаки, виправлено).
local lastWorkspaceScrollBind

local function table_value(value, ...)
    if value == nil then
        return nil
    end

    for _, key in ipairs({ ... }) do
        local ok, item = pcall(function()
            return value[key]
        end)

        if ok and item ~= nil then
            return item
        end
    end

    return nil
end

local function last_workspace_state()
    local monitor = hl.get_monitor_at_cursor() or hl.get_active_monitor()
    if not monitor then
        return false, nil
    end

    local activeWorkspace = table_value(monitor, "active_workspace")
    local activeWorkspaceId = table_value(activeWorkspace, "id")
    if type(activeWorkspaceId) ~= "number" or activeWorkspaceId <= 0 then
        return false, nil
    end

    local activeWorkspaceWindows = table_value(activeWorkspace, "windows")
    if type(activeWorkspaceWindows) ~= "number" or activeWorkspaceWindows == 0 then
        return false, nil
    end

    local lastWorkspaceId
    for _, workspace in ipairs(hl.get_workspaces()) do
        local id = table_value(workspace, "id")

        if type(id) == "number"
            and id > 0
            and table_value(workspace, "special") ~= true
            and table_value(workspace, "monitor") == monitor then
            lastWorkspaceId = math.max(lastWorkspaceId or id, id)
        end
    end

    return activeWorkspaceId == lastWorkspaceId, monitor
end

local function create_workspace_at_end()
    local isLastWorkspace, monitor = last_workspace_state()
    if not isLastWorkspace or not monitor then
        return
    end

    hl.dispatch(hl.dsp.focus({ monitor = table_value(monitor, "name") }))
    hl.dispatch(hl.dsp.focus({ workspace = "emptynm" }))
end

local function update_last_workspace_scroll_bind()
    if not lastWorkspaceScrollBind then
        return
    end

    local enabled = false
    if hl.get_current_submap() == "scrolloverview" then
        enabled = last_workspace_state()
    end

    lastWorkspaceScrollBind:set_enabled(enabled)
end

-- Власний submap замість вбудованої клавіатурної навігації overview
-- (https://github.com/yayuuu/hyprland-scroll-overview/wiki/Keybind-submap) --
-- потрібен ЯК ОСНОВА для mouse_down-біндa динамічних робочих просторів
-- (вікі explicitly каже не визначати submap вдруге, якщо він вже є).
-- Поведінка стрілок/Enter/Escape/кліків тут -- точна копія дефолтної
-- вбудованої, просто тепер явно прописана, щоб було куди додати mouse_down.
hl.define_submap("scrolloverview", function()
    hl.bind("left",   hl.plugin.scrolloverview.navigate("left"))
    hl.bind("right",  hl.plugin.scrolloverview.navigate("right"))
    hl.bind("up",     hl.plugin.scrolloverview.navigate("up"))
    hl.bind("down",   hl.plugin.scrolloverview.navigate("down"))
    hl.bind("return", hl.plugin.scrolloverview.overview("select"))
    hl.bind("escape", hl.plugin.scrolloverview.overview("off"))
    hl.bind("mouse:272", function()
        hl.plugin.scrolloverview.overview("select")
        hl.plugin.scrolloverview.window("select")
        hl.plugin.scrolloverview.overview("off")
    end, { mouse = true })
    hl.bind("mouse:274", hl.plugin.scrolloverview.window("close"), { mouse = true })

    -- mouse_down у звичайному стані вимкнений (built-in скрол overview працює
    -- як завжди) -- вмикається лише коли курсор на ОСТАННЬОМУ непорожньому
    -- робочому столі монітора; тоді наступний скрол "вниз" створює новий
    -- порожній простір і перемикається на нього замість нічого не робити.
    lastWorkspaceScrollBind = hl.bind("mouse_down", create_workspace_at_end)
    lastWorkspaceScrollBind:set_enabled(false)
end)

hl.on("workspace.active", update_last_workspace_scroll_bind)
hl.on("workspace.created", update_last_workspace_scroll_bind)
hl.on("workspace.removed", update_last_workspace_scroll_bind)
hl.on("workspace.move_to_monitor", update_last_workspace_scroll_bind)
hl.on("window.open", update_last_workspace_scroll_bind)
hl.on("window.close", update_last_workspace_scroll_bind)
hl.on("window.move_to_workspace", update_last_workspace_scroll_bind)
hl.on("monitor.focused", update_last_workspace_scroll_bind)
hl.on("keybinds.submap", update_last_workspace_scroll_bind)

local lastWorkspaceScrollTimer = hl.timer(update_last_workspace_scroll_bind, {
    timeout = 50,
    type = "repeat",
})

update_last_workspace_scroll_bind()

