-- Nebula OS: базовий конфіг Hyprland (монітори, інпут, лейаут, автозапуск, хоткеї).
-- Живий файл (crew/hyprland/default.nix підключає його через mkOutOfStoreSymlink) —
-- редагується напряму, Hyprland підхоплює зміни на льоту, без `nh os switch`.
--
-- Візуальний tweaking (blur/анімації/border/rounding) — окремо, у tweaks.lua,
-- підключений нижче через require.

hl.config({ autogenerated = false })

-- Нового заліза (Arc A770) ще нема — поки що "preferred", auto-позиція.
-- Повернутись і прописати точний режим/позицію, коли прийде новий білд.
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })

hl.config({
  input = {
    -- Та сама розкладка, що й у core/system.nix (services.xserver.xkb) і
    -- crew/bspwm.nix — тримати всі три копії в синхроні при зміні розкладки.
    kb_layout = "us,ua,de",
    kb_options = "grp:alt_shift_toggle",
  },
})

require("tweaks")

local terminal = "wezterm"

hl.on("hyprland.start", function()
    -- graphical-session.target (те, до чого прив'язаний home-manager-івський
    -- noctalia.service через WantedBy) ніколи сам не активується для
    -- Hyprland на NixOS, а `systemctl --user start graphical-session.target`
    -- напряму падає з "RefuseManualStart" -- це системний static-таргет,
    -- його не можна стартувати вручну. Живо перевірено: єдиний робочий шлях
    -- -- стартувати сам noctalia.service напряму, в обхід таргету.
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user start noctalia.service")
    hl.exec_cmd(terminal)
end)

-- Awakened PoE Trade -- встановлений, оверлей/тултіп працює (no_blur,
-- клікабельні кнопки гри через --ozone-platform=x11, дивись
-- crew/hyprland/default.nix), АЛЕ Ctrl+D (і всі інші дії, завʼязані на
-- electron-overlay-window) НЕ ПРАЦЮЮТЬ і не запрацюють без патчу поза
-- розумним обсягом: Hyprland 0.55.4 лишає X11-властивість
-- _NET_ACTIVE_WINDOW як 0x0 для XWayland-клієнтів (підтверджено `xprop
-- -root`), а саме на неї спирається electron-overlay-window, щоб
-- зрозуміти, що гра активна, і зареєструвати глобальний Ctrl+D. no_focus
-- тут не зайвий (без нього вікно оверлею іноді перехоплює Hyprland-фокус),
-- але кореневу причину не лікує. Community-рецепт з
-- SnosMe/awakened-poe-trade#1137. Основний прайс-чекер на Hyprland --
-- poe-price-check (нижче), саме через цю причину.
hl.window_rule({
    name  = "awakened-poe-trade-overlay",
    match = { class = "^awakened-poe-trade$" },

    float = true,
    no_blur = true,
    no_focus = true,
    no_shadow = true,
    border_size = 0,
    pin = true,
})

-- poe-price-check -- tkinter override_redirect вікно. Пробували windowrule
-- (pin, stay_focused, окремо й разом) -- жоден комбо не прибрав ні
-- неклікабельність, ні "втечу" кліків на PoE при перемиканні workspace, поки
-- попап показаний. Висновок: це не лагодиться на рівні windowrule --
-- override_redirect / XWayland-легасі, яке Hyprland просто не розуміє так,
-- як X11 (підтверджено самим мейнтейнером Hyprland, issue #2365). Реальний
-- фікс -- переписати UI на GTK + layer-shell (нативний Wayland), окремий,
-- більший follow-up.

-- Основні
hl.bind("SUPER + Return", hl.dsp.exec_cmd(terminal))
hl.bind("SUPER + D", hl.dsp.exec_cmd("fuzzel"))
-- poe-price-check -- основний прайс-чекер на Hyprland (crew/poe-price-check.nix
-- біндить те саме на super+p через sxhkd, але sxhkd -- X11-демон з bspwm-сесії,
-- на Hyprland він не піднятий; тут окремий, нативний Hyprland-бінд, який не
-- залежить від фокус-трекінгу XWayland/electron-overlay-window взагалі).
hl.bind("SUPER + P", hl.dsp.exec_cmd("poe-price-check"))
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER + F", hl.dsp.window.fullscreen({}))
hl.bind("SUPER + SHIFT + Space", hl.dsp.window.float({}))

-- Фокус між вікнами
hl.bind("SUPER + Left", hl.dsp.focus({ direction = "l" }))
hl.bind("SUPER + Right", hl.dsp.focus({ direction = "r" }))
hl.bind("SUPER + Up", hl.dsp.focus({ direction = "u" }))
hl.bind("SUPER + Down", hl.dsp.focus({ direction = "d" }))

-- Робочі простори 1-9: SUPER — перейти, SUPER+SHIFT — перекинути вікно
for i = 1, 9 do
    hl.bind("SUPER + " .. i, hl.dsp.focus({ workspace = i }))
    hl.bind("SUPER + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end
