-- Nebula OS: базовий конфіг Hyprland (монітори, інпут, лейаут, автозапуск, хоткеї).
-- Живий файл (crew/hyprland/default.nix підключає його через mkOutOfStoreSymlink) —
-- редагується напряму, Hyprland підхоплює зміни на льоту, без `nh os switch`.
--
-- Візуальний tweaking (blur/анімації/border/rounding) — окремо, у tweaks.lua,
-- підключений нижче через require.

hl.config({ autogenerated = false })

-- Нового заліза (Arc A770) ще нема — поки що "preferred", auto-позиція.
-- Повернутись і прописати точний режим/позицію, коли прийде новий білд.
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })

hl.config({
  input = {
    -- Та сама розкладка, що й у core/system.nix (services.xserver.xkb) і
    -- crew/bspwm.nix — тримати всі три копії в синхроні при зміні розкладки.
    kb_layout = "us,ua,de",
    kb_options = "grp:alt_shift_toggle",
    -- follow_mouse=0 -- перевірено вдруге, з живим EE2, PoE все одно
    -- перехоплював контроль. Не той фікс, прибрано остаточно. Реальна
    -- причина зникання попапу при наведенні -- власна uiohook-логіка
    -- застосунку (AreaTracker: рух миші без утримання Ctrl понад
    -- closeThreshold = сигнал "сховати", ніяк не пов'язано з Hyprland-
    -- фокусом), а "PoE перехоплює контроль на інших workspace" -- та сама
    -- причина, що й із poe-price-check: `pin = true` (див. нижче).
  },
})

require("tweaks")

local terminal = "wezterm"

hl.on("hyprland.start", function()
    -- graphical-session.target (те, до чого прив'язаний home-manager-івський
    -- noctalia.service через WantedBy) ніколи сам не активується для
    -- Hyprland на NixOS, а `systemctl --user start graphical-session.target`
    -- напряму падає з "RefuseManualStart" -- це системний static-таргет,
    -- його не можна стартувати вручну. Живо перевірено: єдиний робочий шлях
    -- -- стартувати сам noctalia.service напряму, в обхід таргету.
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user start noctalia.service")
    hl.exec_cmd(terminal)
end)

-- Awakened PoE Trade -- встановлений, оверлей/тултіп працює (no_blur,
-- клікабельні кнопки гри через --ozone-platform=x11, дивись
-- crew/hyprland/default.nix). Раніше тут стояв no_focus, і з ним Ctrl+D не
-- працював -- висновок був "Hyprland 0.55.4 не виставляє _NET_ACTIVE_WINDOW
-- для XWayland, не лагодиться". 2026-09-27: Exiled Exchange 2 (той самий
-- electron-overlay-window/uiohook-napi код, PoE2-форк Awakened) отримав
-- ІДЕНТИЧНЕ правило БЕЗ no_focus -- і Ctrl+D в ньому працює одразу, живо
-- підтверджено. Тобто справжня причина провалу в Awakened, схоже, був саме
-- no_focus (заважав XWM-у Hyprland коректно віддавати фокус назад грі), а
-- не непоборний ліміт компоситора -- прибрано, ПОТРІБЕН повторний живий
-- тест Ctrl+D в PoE1.
-- pin теж прибрано (та сама причина, що й у poe-price-check нижче: pinned
-- вікно "тікає" на всі workspace одночасно, і клік на ІНШОМУ workspace
-- плутано роутиться на гру -- живо підтверджено з EE2 2026-09-27).
hl.window_rule({
    name  = "awakened-poe-trade-overlay",
    match = { class = "^awakened-poe-trade$" },

    float = true,
    no_blur = true,
    no_shadow = true,
    border_size = 0,
})

-- Exiled Exchange 2 (PoE2) -- той самий рецепт, АЛЕ без no_focus (див.
-- коментар вище над awakened-poe-trade-overlay) -- живо підтверджено:
-- Ctrl+D працює. class з .desktop (StartupWMClass=Exiled Exchange 2) міг
-- відрізнятись від реального runtime app-id (як і в Awakened, де
-- StartupWMClass не збігався з "awakened-poe-trade") -- обидва варіанти
-- про всяк випадок.
hl.window_rule({
    name  = "exiled-exchange-2-overlay",
    match = { class = "^Exiled Exchange 2$" },

    float = true,
    no_blur = true,
    no_shadow = true,
    border_size = 0,
})
hl.window_rule({
    name  = "exiled-exchange-2-overlay-lc",
    match = { class = "^exiled-exchange-2$" },

    float = true,
    no_blur = true,
    no_shadow = true,
    border_size = 0,
})

-- Рулетка (surf) -- floating, розмір під контент (колесо 360px + кнопки/
-- редактор списку), по центру екрана, а не на весь tiled-простір.
hl.window_rule({
    name  = "roulette-surf",
    match = { class = "^Surf$" },

    float = true,
    size  = "460 700",
    center = true,
})

-- Калькулятор (Qalculate) -- floating, компактний розмір замість
-- дефолтного 1261x1382 (tiled на весь простір).
hl.window_rule({
    name  = "qalculate-gtk",
    match = { class = "^qalculate-gtk$" },

    float = true,
    size  = "460 620",
    center = true,
})

-- poe-price-check -- tkinter override_redirect вікно. Пробували windowrule
-- (pin, stay_focused, окремо й разом) -- жоден комбо не прибрав ні
-- неклікабельність, ні "втечу" кліків на PoE при перемиканні workspace, поки
-- попап показаний. Висновок: це не лагодиться на рівні windowrule --
-- override_redirect / XWayland-легасі, яке Hyprland просто не розуміє так,
-- як X11 (підтверджено самим мейнтейнером Hyprland, issue #2365). Реальний
-- фікс -- переписати UI на GTK + layer-shell (нативний Wayland), окремий,
-- більший follow-up.

-- Основні
hl.bind("SUPER + Return", hl.dsp.exec_cmd(terminal))
hl.bind("SUPER + D", hl.dsp.exec_cmd("noctalia msg panel-toggle launcher"))
-- poe-price-check -- основний прайс-чекер на Hyprland (crew/poe-price-check.nix
-- біндить те саме на super+p через sxhkd, але sxhkd -- X11-демон з bspwm-сесії,
-- на Hyprland він не піднятий; тут окремий, нативний Hyprland-бінд, який не
-- залежить від фокус-трекінгу XWayland/electron-overlay-window взагалі).
hl.bind("SUPER + P", hl.dsp.exec_cmd("poe-price-check"))
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER + F", hl.dsp.window.fullscreen({}))
hl.bind("SUPER + SHIFT + Space", hl.dsp.window.float({}))
-- Pin -- закріпити плаваюче вікно поверх усіх воркспейсів (той самий
-- super+shift+p, що й always-on-top у crew/bspwm.nix). Не floating-вікно
-- pin просто ігнорує -- спершу SUPER+SHIFT+Space.
hl.bind("SUPER + SHIFT + P", hl.dsp.window.pin())

-- Скріншоти -- Noctalia сама це вміє (noctalia msg), той самий набір, що й
-- maim/xclip-біндами в crew/bspwm.nix (Print/super+shift+s).
hl.bind("Print", hl.dsp.exec_cmd("noctalia msg screenshot-fullscreen"))
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("noctalia msg screenshot-region"))

-- Переміщення/зміна розміру вікна мишею: SUPER + ЛКМ тягне, SUPER + ПКМ
-- ресайзить (mouse:272/273 -- стандартні коди кнопок з офіційного
-- дефолтного hyprland.lua, mouse=true обов'язковий для mouse-біндів).
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Порт решти кастомних bspwm-біндів (crew/bspwm.nix) під Hyprland. Де
-- Noctalia сама вміє те саме (noctalia msg) -- береться саме воно, а не
-- окремий X11-інструмент/скрипт: лок, power-menu, dpms, theme, wallpaper,
-- caffeine (=nebula-awake), clipboard-історія, window switcher.
hl.bind("SUPER + Escape", hl.dsp.exec_cmd("noctalia msg session lock"))
hl.bind("SUPER + SHIFT + E", hl.dsp.exec_cmd("noctalia msg panel-toggle session"))
hl.bind("SUPER + SHIFT + Escape", hl.dsp.exec_cmd("noctalia msg dpms-off"))
hl.bind("SUPER + N", hl.dsp.exec_cmd("noctalia msg theme-mode-toggle"))
hl.bind("SUPER + W", hl.dsp.exec_cmd("noctalia msg panel-toggle wallpaper"))
hl.bind("SUPER + SHIFT + A", hl.dsp.exec_cmd("noctalia msg caffeine-toggle"))
hl.bind("SUPER + V", hl.dsp.exec_cmd("noctalia msg panel-toggle clipboard"))
hl.bind("SUPER + Tab", hl.dsp.exec_cmd("noctalia msg window-switcher"))

-- Немає нативного еквіваленту в Noctalia -- лишаються окремими
-- інструментами/скриптами (nwg-look конфігурує GTK-тему застосунків
-- взагалі, не саму Noctalia, тож не замінюється).
hl.bind("SUPER + SHIFT + O", hl.dsp.exec_cmd("nebula-ocr-wl"))
hl.bind("SUPER + SHIFT + X", hl.dsp.exec_cmd("nebula-color-picker-wl"))
hl.bind("SUPER + SHIFT + T", hl.dsp.exec_cmd("nwg-look"))
hl.bind("SUPER + SHIFT + V", hl.dsp.exec_cmd("pavucontrol"))
-- surf замість xdg-open -- окреме вікно без вкладок/адресного рядка
-- браузера, той самий готовий HTML/CSS/JS без переписування.
hl.bind("SUPER + SHIFT + R", hl.dsp.exec_cmd(
    "surf file://" .. os.getenv("HOME") .. "/nebula-config/assets/cprogram/roulette.html"
))
hl.bind("SUPER + SHIFT + M", hl.dsp.exec_cmd(
    "sh -c 'cd ~/Applications/SwiftpointX1 && ./\"Swiftpoint X1 Control Panel\"'"
))
hl.bind("SUPER + SHIFT + C", hl.dsp.exec_cmd(
    'wezterm start --always-new-process -- sh -c "cd ~/Projects/ascension-limitless-progression && nix develop --command ./gradlew runClient"'
))
hl.bind("SUPER + Equal", hl.dsp.exec_cmd("qalculate-gtk"))

-- Медіа/яскравість -- ті самі команди, що й у crew/bspwm.nix, портативні
-- (wpctl/brightnessctl не залежать від X11/bspwm).
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"))

-- Фокус між вікнами
hl.bind("SUPER + Left", hl.dsp.focus({ direction = "l" }))
hl.bind("SUPER + Right", hl.dsp.focus({ direction = "r" }))
hl.bind("SUPER + Up", hl.dsp.focus({ direction = "u" }))
hl.bind("SUPER + Down", hl.dsp.focus({ direction = "d" }))

-- Робочі простори 1-9: SUPER — перейти, SUPER+SHIFT — перекинути вікно
for i = 1, 9 do
    hl.bind("SUPER + " .. i, hl.dsp.focus({ workspace = i }))
    hl.bind("SUPER + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end

